/*
******************************************************************************
File:     mcu.h
Info:     Generated by Atollic TrueSTUDIO(R) 8.0.0   2017-08-19

The MIT License (MIT)
Copyright (c) 2009-2017 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/**
 **===========================================================================
 **  Revisions
 **===========================================================================
 **       Date        Modification
 **       2011-09-07  First issue.
 **       2011-11-07  Added new devices
 **       2013-05-17  Added new devices
 **       2013-10-21  Added new devices
 **       2014-01-15  Added new devices
 **       2014-05-15  Added new devices
 **       2014-09-15  Added new devices
 **       2014-12-16  Added new devices
 **       2015-03-20  Added new devices
 **       2015-06-23  Added new devices
 **       2015-10-12  Updated MKV4x devices
 **       2016-03-08  Added new devices
 **===========================================================================
 */

#ifndef __MCU_H
#define __MCU_H

/* Include MCU and system start-up header file */

#if defined(MKE02Z2)
  #include "MKE02Z2.h"
  #include "system_MKE02Z2.h"
#elif defined(MKE02Z4)
  #include "MKE02Z2.h"
  #include "system_MKE02Z2.h"
#elif defined(MKE04Z4)
  #include "MKE04Z4.h"
  #include "system_MKE04Z4.h"
#elif defined(MKE04Z1284)
  #include "MKE04Z1284.h"
  #include "system_MKE04Z1284.h"
#elif defined(MKE06Z4)
  #include "MKE06Z4.h"
  #include "system_MKE06Z4.h"
#elif defined(MKE14Z7)
  #include "MKE14Z7.h"
  #include "system_MKE14Z7.h"
#elif defined(MKE15Z7)
  #include "MKE15Z7.h"
  #include "system_MKE15Z7.h"
#elif defined(SKEAZN84)
  #include "SKEAZN84.h"
  #include "system_SKEAZN84.h"
#elif defined(SKEAZN642)
  #include "SKEAZN642.h"
  #include "system_SKEAZN642.h"
#elif defined(SKEAZ1284)
  #include "SKEAZ1284.h"
  #include "system_SKEAZ1284.h"
#elif defined(MKL02Z4)
  #include "MKL02Z4.h"
  #include "system_MKL02Z4.h"
#elif defined(MKL03Z4)
  #include "MKL03Z4.h"
  #include "system_MKL03Z4.h"
#elif defined(MKL04Z4)
  #include "MKL04Z4.h"
  #include "system_MKL04Z4.h"
#elif defined(MKL05Z4)
  #include "MKL05Z4.h"
  #include "system_MKL05Z4.h"
#elif defined(MKL13Z644)
  #include "MKL13Z644.h"
  #include "system_MKL13Z644.h"
#elif defined(MKL14Z4)
  #include "MKL14Z4.h"
  #include "system_MKL14Z4.h"
#elif defined(MKL15Z4)
  #include "MKL15Z4.h"
  #include "system_MKL15Z4.h"
#elif defined(MKL16Z4)
  #include "MKL16Z4.h"
  #include "system_MKL16Z4.h"
#elif defined(MKL17Z4)
  #include "MKL17Z4.h"
  #include "system_MKL17Z4.h"
#elif defined(MKL17Z644)
  #include "MKL17Z644.h"
  #include "system_MKL17Z644.h"
#elif defined(MKL24Z4)
  #include "MKL24Z4.h"
  #include "system_MKL24Z4.h"
#elif defined(MKL25Z4)
  #include "MKL25Z4.h"
  #include "system_MKL25Z4.h"
#elif defined(MKL26Z4)
  #include "MKL26Z4.h"
  #include "system_MKL26Z4.h"
#elif defined(MKL27Z4)
  #include "MKL27Z4.h"
  #include "system_MKL27Z4.h"
#elif defined(MKL27Z644)
  #include "MKL27Z644.h"
  #include "system_MKL27Z644.h"
#elif defined(MKL28Z7)
  #include "MKL28Z7.h"
  #include "system_MKL28Z7.h"
#elif defined(MKL33Z4)
  #include "MKL33Z4.h"
  #include "system_MKL33Z4.h"
#elif defined(MKL33Z644)
  #include "MKL33Z644.h"
  #include "system_MKL33Z644.h"
#elif defined(MKL34Z4)
  #include "MKL34Z4.h"
  #include "system_MKL34Z4.h"
#elif defined(MKL36Z4)
  #include "MKL36Z4.h"
  #include "system_MKL36Z4.h"
#elif defined(MKL43Z4)
  #include "MKL43Z4.h"
  #include "system_MKL43Z4.h"
#elif defined(MKL46Z4)
  #include "MKL46Z4.h"
  #include "system_MKL46Z4.h"
#elif defined(MKL82Z7)
  #include "MKL82Z7.h"
  #include "system_MKL82Z7.h"
#elif defined(MKW01Z4)
  #include "MKW01Z4.h"
  #include "system_MKW01Z4.h"
#elif defined(MKW21D5)
  #include "MKW21D5.h"
  #include "system_MKW21D5.h"
#elif defined(MKW22D5)
  #include "MKW22D5.h"
  #include "system_MKW22D5.h"
#elif defined(MKW24D5)
  #include "MKW24D5.h"
  #include "system_MKW24D5.h"
#elif defined(MKW20Z4)
  #include "MKW20Z4.h"
  #include "system_MKW20Z4.h"
#elif defined(MKW30Z4)
  #include "MKW30Z4.h"
  #include "system_MKW30Z4.h"
#elif defined(MKW40Z4)
  #include "MKW40Z4.h"
  #include "system_MKW40Z4.h"
#elif defined(MKW21Z4)
  #include "MKW21Z4.h"
  #include "system_MKW21Z4.h"
#elif defined(MKW31Z4)
  #include "MKW31Z4.h"
  #include "system_MKW31Z4.h"
#elif defined(MKW41Z4)
  #include "MKW41Z4.h"
  #include "system_MKW41Z4.h"
#elif defined(MKM14Z5)
  #include "MKM14Z5.h"
  #include "system_MKM14Z5.h"
#elif defined(MKM14ZA5)
  #include "MKM14ZA5.h"
  #include "system_MKM14ZA5.h"
#elif defined(MKM33Z5)
  #include "MKM33Z5.h"
  #include "system_MKM33Z5.h"
#elif defined(MKM33ZA5)
  #include "MKM33ZA5.h"
  #include "system_MKM33ZA5.h"
#elif defined(MKM34Z5)
  #include "MKM34Z5.h"
  #include "system_MKM34Z5.h"
#elif defined(MKM34ZA5)
  #include "MKM34ZA5.h"
  #include "system_MKM34ZA5.h"
#elif defined(MKM34Z7)
  #include "MKM34Z7.h"
  #include "system_MKM34Z7.h"
#elif defined(MKV10Z7)
  #include "MKV10Z7.h"
  #include "system_MKV10Z7.h"
#elif defined(MKV10Z1287)
  #include "MKV10Z1287.h"
  #include "system_MKV10Z1287.h"
#elif defined(MKV11Z7)
  #include "MKV11Z7.h"
  #include "system_MKV11Z7.h"
#elif defined(MKV30F12810)
  #include "MKV30F12810.h"
  #include "system_MKV30F12810.h"
#elif defined(MKV31F12810)
  #include "MKV31F12810.h"
  #include "system_MKV31F12810.h"
#elif defined(MKV31F25612)
  #include "MKV31F25612.h"
  #include "system_MKV31F25612.h"
#elif defined(MKV31F51212)
  #include "MKV31F51212.h"
  #include "system_MKV31F51212.h"
#elif defined(MKV42F16)
  #include "MKV42F16.h"
  #include "system_MKV42F16.h"
#elif defined(MKV44F16)
  #include "MKV44F16.h"
  #include "system_MKV44F16.h"
#elif defined(MKV46F16)
  #include "MKV46F16.h"
  #include "system_MKV46F16.h"
#elif defined(MKV56F22)
  #include "MKV56F22.h"
  #include "system_MKV56F22.h"
#elif defined(MKV58F22)
  #include "MKV58F22.h"
  #include "system_MKV58F22.h"
#elif defined(MKV56F24)
  #include "MKV56F24.h"
  #include "system_MKV56F24.h"
#elif defined(MKV58F24)
  #include "MKV58F24.h"
  #include "system_MKV58F24.h"
#elif defined(MK02Fxxx10)
  #include "MK02F12810.h"
  #include "system_MK02F12810.h"
#elif defined(MK10D5)
  #include "MK10D5.h"
  #include "system_MK10D5.h"
#elif defined(MK10D7)
  #include "MK10D7.h"
  #include "system_MK10D7.h"
#elif defined(MK10DN512Vyy10) || defined(MK10DX128Vyy10) || defined(MK10DX256Vyy10)
  #include "MK10DZ10.h"
  #include "system_MK10DZ10.h"
#elif defined(MK10N512VLQ100) || defined(MK10N512VMD100) || defined(MK10X256VLQ100) || defined(MK10X256VMD100)
  #include "MK10DZ10.h"
  #include "system_MK10DZ10.h"
#elif defined(MK11D5)
  #include "MK11D5.h"
  #include "system_MK11D5.h"
#elif defined(MK11DA5)
  #include "MK11DA5.h"
  #include "system_MK11DA5.h"
#elif defined(MK12D5)
  #include "MK12D5.h"
  #include "system_MK12D5.h"
#elif defined(MK20DN512Vyy10) || defined(MK20DX128Vyy10) || defined(MK20DX256Vyy10)
  #include "MK20DZ10.h"
  #include "system_MK20DZ10.h"
#elif defined(MK20Dx32Vyy5) || defined(MK20Dx64Vyy5) || defined(MK20DX128Vyy5)
  #include "MK20D5.h"
  #include "system_MK20D5.h"
#elif defined(MK20DX64Vyy7) || defined(MK20DX128Vyy7) || defined(MK20DX256Vyy7)
  #include "MK20D7.h"
  #include "system_MK20D7.h"
#elif defined(MK20N512VLL100) || defined(MK20N512VLQ100) || defined(MK20N512VMD100) || defined(MK20X256VMD100)
  #include "MK20DZ10.h"
  #include "system_MK20DZ10.h"
#elif defined(MK21D5)
  #include "MK21D5.h"
  #include "system_MK21D5.h"
#elif defined(MK21DA5)
  #include "MK21DA5.h"
  #include "system_MK21DA5.h"
#elif defined(MK22D5)
  #include "MK22D5.h"
  #include "system_MK22D5.h"
#elif defined(MK22FN12810)
  #include "MK22F12810.h"
  #include "system_MK22F12810.h"
#elif defined(MK22FN25612)
  #include "MK22F25612.h"
  #include "system_MK22F25612.h"
#elif defined(MK22FN51212)
  #include "MK22F51212.h"
  #include "system_MK22F51212.h"
#elif defined(MK30D7)
  #include "MK30D7.h"
  #include "system_MK30D7.h"
#elif defined(MK30DN512Vyy10) || defined(MK30DX128Vyy10) || defined(MK30DX256Vyy10)
  #include "MK30DZ10.h"
  #include "system_MK30DZ10.h"
#elif defined(MK30N512VLL100) || defined(MK30N512VLQ100) || defined(MK30N512VMD100) || defined(MK30X256VLQ100) || defined(MK30X256VMD100)
  #include "MK30DZ10.h"
  #include "system_MK30DZ10.h"
#elif defined(MK40D7)
  #include "MK40D7.h"
  #include "system_MK40D7.h"
#elif defined(MK40DN512Vyy10) || defined(MK40DX128Vyy10) || defined(MK40DX256Vyy10)
  #include "MK40DZ10.h"
  #include "system_MK40DZ10.h"
#elif defined(MK40N512VLL100) || defined(MK40N512VLQ100) || defined(MK40N512VMD100) || defined(MK40X256VLQ100) || defined(MK40X256VMD100) || defined(MK40X512VLQ100)
  #include "MK40DZ10.h"
  #include "system_MK40DZ10.h"
#elif defined(MK50D7)
  #include "MK50D7.h"
  #include "system_MK50D7.h"
#elif defined(MK51D7)
  #include "MK51D7.h"
  #include "system_MK51D7.h"
#elif defined(MK50DN512ZCyy10) || defined(MK50DX256ZCyy10)
  #include "MK50DZ10.h"
  #include "system_MK50DZ10.h"
#elif defined(MK50N512CMD100) || defined(MK50N512CMD100)
  #include "MK50DZ10.h"
  #include "system_MK50DZ10.h"
#elif defined(MK51DN256ZCyy10) || defined(MK51DN512ZCyy10) || defined(MK51DX256ZCyy10)
  #include "MK51DZ10.h"
  #include "system_MK51DZ10.h"
#elif defined(MK51N256CMD100) || defined(MK51N512CLQ100) || defined(MK51N512CMD100)
  #include "MK51DZ10.h"
  #include "system_MK51DZ10.h"
#elif defined(MK52DN512ZCyy10)
  #include "MK52DZ10.h"
  #include "system_MK52DZ10.h"
#elif defined(MK52N512CLQ100) || defined(MK52N512CMD100)
  #include "MK52DZ10.h"
  #include "system_MK52DZ10.h"
#elif defined(MK53DN512ZCyy10) || defined(MK53DX256ZCyy10)
  #include "MK53DZ10.h"
  #include "system_MK53DZ10.h"
#elif defined(MK53N512CLQ100) || defined(MK53N512CMD100) || defined(MK53X256CLQ100) || defined(MK53X256CMD100)
  #include "MK53DZ10.h"
  #include "system_MK53DZ10.h"
#elif defined(MK60DN256Vyy10) || defined(MK60DN512Vyy10) || defined(MK60DX256Vyy10)
  #include "MK60DZ10.h"
  #include "system_MK60DZ10.h"
#elif defined(MK60FN1M0Vyy12) || defined(MK60FX512Vyy12)
  #include "MK60DZ12.h"
  #include "system_MK60DZ12.h"
#elif defined(MK60FN1M0Vyy15) || defined(MK60FX512Vyy15)
  #include "MK60DZ15.h"
  #include "system_MK60DZ15.h"
#elif defined(MK60N256VLL100) || defined(MK60N256VLQ100) || defined(MK60N256VMD100) || defined(MK60N512CAB100) || defined(MK60N512CAB100R) || defined(MK60N512VLL100) || defined(MK60N512VLQ100) || defined(MK60N512VMD100) || defined(MK60X256VLL100) || defined(MK60X256VLQ100) || defined(MK60X256VMD100)
  #include "MK60DZ10.h"
  #include "system_MK60DZ10.h"
#elif defined(MK61FN1M0Vyy12) || defined(MK61FX512Vyy12)
  #include "MK61DZ12.h"
  #include "system_MK61DZ12.h"
#elif defined(MK61FN1M0Vyy15) || defined(MK61FX512Vyy15)
  #include "MK61DZ15.h"
  #include "system_MK61DZ15.h"
#elif defined(MWPR1516)
  #include "MWPR1516.h"
  #include "system_MWPR1516.h"
#else
  #error Include correct header files for your device here!
#endif

#endif
