/*
******************************************************************************
File:     startup_MKV58F22.s
Info:     Generated by Atollic TrueSTUDIO(R) 8.0.0   2017-08-19

The MIT License (MIT)
Copyright (c) 2009-2017 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

  .syntax unified
  .cpu cortex-m4
  .fpu softvfp
  .thumb

.global Reset_Handler
.global InterruptVector
.global Default_Handler

/* Linker script definitions */
/* start address for the initialization values of the .data section */
.word _sidata
/* start address for the .data section */
.word _sdata
/* end address for the .data section */
.word _edata
/* start address for the .bss section */
.word _sbss
/* end address for the .bss section */
.word _ebss


/**
**===========================================================================
**  Program - Reset_Handler
**  Abstract: This code gets called after reset.
**===========================================================================
*/
  .section  .text.Reset_Handler,"ax", %progbits
  .type Reset_Handler, %function
Reset_Handler:
  /* Set stack pointer */
  ldr sp,=_estack

  /* Branch to SystemInit function */
  bl SystemInit

  /* Copy data initialization values */
  ldr r1,=_sidata
  ldr r2,=_sdata
  ldr r3,=_edata
  b cmpdata
CopyLoop:
  ldr r0, [r1], #4
  str r0, [r2], #4
cmpdata:
  cmp r2, r3
  blt CopyLoop

  /* Clear BSS section */
  movs r0, #0
  ldr r2,=_sbss
  ldr r3,=_ebss
  b cmpbss
ClearLoop:
  str r0, [r2], #4
cmpbss:
  cmp r2, r3
  blt ClearLoop

  /* Call static constructors */
  bl __libc_init_array

  /* Branch to main */
  bl main

  /* If main returns, branch to Default_Handler. */
  b Default_Handler

  .size  Reset_Handler, .-Reset_Handler

/**
**===========================================================================
**  Program - Default_Handler
**  Abstract: This code gets called when the processor receives an
**    unexpected interrupt.
**===========================================================================
*/
  .section  .text.Default_Handler,"ax", %progbits
Default_Handler:
  b  Default_Handler

  .size  Default_Handler, .-Default_Handler

/**
**===========================================================================
**  Interrupt vector table
**===========================================================================
*/
  .section .isr_vector,"a", %progbits
InterruptVector:
  .word _estack                   /* 0 - Stack pointer */
  .word Reset_Handler             /* 1 - Reset */
  .word NMI_Handler               /* 2 - NMI  */
  .word HardFault_Handler         /* 3 - Hard fault */
  .word MemManage_Handler         /* 4 - Memory management fault */
  .word BusFault_Handler          /* 5 - Bus fault */
  .word UsageFault_Handler        /* 6 - Usage fault */
  .word 0                         /* 7 - Reserved */
  .word 0                         /* 8 - Reserved */
  .word 0                         /* 9 - Reserved */
  .word 0                         /* 10 - Reserved */
  .word SVC_Handler               /* 11 - SVCall */
  .word DebugMon_Handler          /* 12 - Reservered for Debug */
  .word 0                         /* 13 - Reserved */
  .word PendSV_Handler            /* 14 - PendSV */
  .word SysTick_Handler           /* 15 - Systick */

  /* External Interrupts */
  .word DMA0_DMA16_IRQHandler                /* DMA channel 0/16 transfer complete*/
  .word DMA1_DMA17_IRQHandler                /* DMA channel 1/17 transfer complete*/
  .word DMA2_DMA18_IRQHandler                /* DMA channel 2/18 transfer complete*/
  .word DMA3_DMA19_IRQHandler                /* DMA channel 3/19 transfer complete*/
  .word DMA4_DMA20_IRQHandler                /* DMA channel 4/20 transfer complete*/
  .word DMA5_DMA21_IRQHandler                /* DMA channel 5/21 transfer complete*/
  .word DMA6_DMA22_IRQHandler                /* DMA channel 6/22 transfer complete*/
  .word DMA7_DMA23_IRQHandler                /* DMA channel 7/23 transfer complete*/
  .word DMA8_DMA24_IRQHandler                /* DMA channel 8/24 transfer complete*/
  .word DMA9_DMA25_IRQHandler                /* DMA channel 9/25 transfer complete*/
  .word DMA10_DMA26_IRQHandler               /* DMA channel 10/26 transfer complete*/
  .word DMA11_DMA27_IRQHandler               /* DMA channel 11/27 transfer complete*/
  .word DMA12_DMA28_IRQHandler               /* DMA channel 12/28 transfer complete*/
  .word DMA13_DMA29_IRQHandler               /* DMA channel 13/29 transfer complete*/
  .word DMA14_DMA30_IRQHandler               /* DMA channel 14/30 transfer complete*/
  .word DMA15_DMA31_IRQHandler               /* DMA channel 15/31 transfer complete*/
  .word DMA_Error_IRQHandler                 /* DMA error interrupt channels 0-31*/
  .word MCM_IRQHandler                       /* MCM normal interrupt*/
  .word FTFE_IRQHandler                      /* FTFL command complete*/
  .word Read_Collision_IRQHandler            /* FTFL read collision*/
  .word PMC_IRQHandler                       /* PMC controller low-voltage detect, low-voltage warning*/
  .word LLWU_IRQHandler                      /* Low leakage wakeup*/
  .word WDOG_EWM_IRQHandler                  /* Single interrupt vector for  WDOG and EWM*/
  .word TRNG0_IRQHandler                     /* True randon number generator*/
  .word I2C0_IRQHandler                      /* Inter-integrated circuit 0*/
  .word I2C1_IRQHandler                      /* Inter-integrated circuit 1*/
  .word SPI0_IRQHandler                      /* Serial peripheral Interface 0*/
  .word SPI1_IRQHandler                      /* Serial peripheral Interface 1*/
  .word UART5_RX_TX_IRQHandler               /* UART5 receive/transmit interrupt*/
  .word UART5_ERR_IRQHandler                 /* UART5 error interrupt*/
  .word UART0_LON_IRQHandler                 /* UART0 LON*/
  .word UART0_RX_TX_IRQHandler               /* UART0 receive/transmit interrupt*/
  .word UART0_ERR_IRQHandler                 /* UART0 error interrupt*/
  .word UART1_RX_TX_IRQHandler               /* UART1 receive/transmit interrupt*/
  .word UART1_ERR_IRQHandler                 /* UART1 error interrupt*/
  .word UART2_RX_TX_IRQHandler               /* UART2 receive/transmit interrupt*/
  .word UART2_ERR_IRQHandler                 /* UART2 error interrupt*/
  .word ADC0_IRQHandler                      /* Analog-to-digital converter 0*/
  .word HSADC_ERR_IRQHandler                 /* High speed analog-to-digital converter zero cross*/
  .word HSADC0_CCA_IRQHandler                /* High speed analog-to-digital converter 0 submodule A scan complete*/
  .word CMP0_IRQHandler                      /* Comparator 0*/
  .word CMP1_IRQHandler                      /* Comparator 1*/
  .word FTM0_IRQHandler                      /* FlexTimer module 0 fault, overflow and channels interrupt*/
  .word FTM1_IRQHandler                      /* FlexTimer module 1 fault, overflow and channels interrupt*/
  .word UART3_RX_TX_IRQHandler               /* UART3 receive/transmit interrupt*/
  .word UART3_ERR_IRQHandler                 /* UART3 error interrupt*/
  .word UART4_RX_TX_IRQHandler               /* UART4 receive/transmit interrupt*/
  .word UART4_ERR_IRQHandler                 /* UART4 error interrupt*/
  .word PIT0_IRQHandler                      /* Periodic interrupt timer channel 0*/
  .word PIT1_IRQHandler                      /* Periodic interrupt timer channel 1*/
  .word PIT2_IRQHandler                      /* Periodic interrupt timer channel 2*/
  .word PIT3_IRQHandler                      /* Periodic interrupt timer channel 3*/
  .word PDB0_IRQHandler                      /* Programmable delay block 0*/
  .word FTM2_IRQHandler                      /* FlexTimer module 2 fault, overflow and channels interrupt*/
  .word XBARA_IRQHandler                     /* Inter-peripheral crossbar switch A*/
  .word PDB1_IRQHandler                      /* Programmable delay block 1*/
  .word DAC0_IRQHandler                      /* Digital-to-analog converter 0*/
  .word MCG_IRQHandler                       /* Multipurpose clock generator*/
  .word LPTMR0_IRQHandler                    /* Low power timer interrupt*/
  .word PORTA_IRQHandler                     /* Port A interrupt*/
  .word PORTB_IRQHandler                     /* Port B interrupt*/
  .word PORTC_IRQHandler                     /* Port C interrupt*/
  .word PORTD_IRQHandler                     /* Port D interrupt*/
  .word PORTE_IRQHandler                     /* Port E interrupt*/
  .word SWI_IRQHandler                       /* Software interrupt*/
  .word SPI2_IRQHandler                      /* Serial peripheral Interface 2*/
  .word ENC_COMPARE_IRQHandler               /* ENC Compare*/
  .word ENC_HOME_IRQHandler                  /* ENC Home*/
  .word ENC_WDOG_SAB_IRQHandler              /* ENC Wdog/SAB*/
  .word ENC_INDEX_IRQHandler                 /* ENC Index/Roll over/Roll Under*/
  .word CMP2_IRQHandler                      /* Comparator 2*/
  .word FTM3_IRQHandler                      /* FlexTimer module 3 fault, overflow and channels*/
  .word Reserved88_IRQHandler                /* Reserved interrupt*/
  .word HSADC0_CCB_IRQHandler                /* High speed analog-to-digital converter 0 submodule B scan complete*/
  .word HSADC1_CCA_IRQHandler                /* High speed analog-to-digital converter 1 submodule C scan complete*/
  .word CAN0_ORed_Message_buffer_IRQHandler  /* Flex controller area network 0 message buffer*/
  .word CAN0_Bus_Off_IRQHandler              /* Flex controller area network 0 bus off*/
  .word CAN0_Error_IRQHandler                /* Flex controller area network 0 error*/
  .word CAN0_Tx_Warning_IRQHandler           /* Flex controller area network 0 transmit*/
  .word CAN0_Rx_Warning_IRQHandler           /* Flex controller area network 0 receive*/
  .word CAN0_Wake_Up_IRQHandler              /* Flex controller area network 0 wake up*/
  .word PWM0_CMP0_IRQHandler                 /* Pulse width modulator A channel 0 compare*/
  .word PWM0_RELOAD0_IRQHandler              /* Pulse width modulator A channel 0 reload*/
  .word PWM0_CMP1_IRQHandler                 /* Pulse width modulator A channel 1 compare*/
  .word PWM0_RELOAD1_IRQHandler              /* Pulse width modulator A channel 1 reload*/
  .word PWM0_CMP2_IRQHandler                 /* Pulse width modulator A channel 2 compare*/
  .word PWM0_RELOAD2_IRQHandler              /* Pulse width modulator A channel 2 reload*/
  .word PWM0_CMP3_IRQHandler                 /* Pulse width modulator A channel 3 compare*/
  .word PWM0_RELOAD3_IRQHandler              /* Pulse width modulator A channel 3 reload*/
  .word PWM0_CAP_IRQHandler                  /* Pulse width modulator A capture*/
  .word PWM0_RERR_IRQHandler                 /* Pulse width modulator A reload error*/
  .word PWM0_FAULT_IRQHandler                /* Pulse width modulator A fault*/
  .word CMP3_IRQHandler                      /* Comparator 3*/
  .word HSADC1_CCB_IRQHandler                /* High speed analog-to-digital converter 1 submodule D scan complete*/
  .word CAN1_ORed_Message_buffer_IRQHandler  /* Flex controller area network 1 message buffer*/
  .word CAN1_Bus_Off_IRQHandler              /* Flex controller area network 1 bus off*/
  .word CAN1_Error_IRQHandler                /* Flex controller area network 1 error*/
  .word CAN1_Tx_Warning_IRQHandler           /* Flex controller area network 1 transmit*/
  .word CAN1_Rx_Warning_IRQHandler           /* Flex controller area network 1 receive*/
  .word CAN1_Wake_Up_IRQHandler              /* Flex controller area network 1 wake up*/
  .word ENET_1588_Timer_IRQHandler           /* Ethernet MAC IEEE 1588 timer*/
  .word ENET_Transmit_IRQHandler             /* Ethernet MAC transmit*/
  .word ENET_Receive_IRQHandler              /* Ethernet MAC receive*/
  .word ENET_Error_IRQHandler                /* Ethernet MAC error and miscelaneous*/
  .word PWM1_CMP0_IRQHandler                 /* Pulse width modulator B channel 0 compare*/
  .word PWM1_RELOAD0_IRQHandler              /* Pulse width modulator B channel 0 reload*/
  .word PWM1_CMP1_IRQHandler                 /* Pulse width modulator B channel 1 compare*/
  .word PWM1_RELOAD1_IRQHandler              /* Pulse width modulator B channel 1 reload*/
  .word PWM1_CMP2_IRQHandler                 /* Pulse width modulator B channel 2 compare*/
  .word PWM1_RELOAD2_IRQHandler              /* Pulse width modulator B channel 2 reload*/
  .word PWM1_CMP3_IRQHandler                 /* Pulse width modulator B channel 3 compare*/
  .word PWM1_RELOAD3_IRQHandler              /* Pulse width modulator B channel 3 reload*/
  .word PWM1_CAP_IRQHandler                  /* Pulse width modulator B capture*/
  .word PWM1_RERR_IRQHandler                 /* Pulse width modulator B reload error*/
  .word PWM1_FAULT_IRQHandler                /* Pulse width modulator B fault*/
  .word CAN2_ORed_Message_buffer_IRQHandler  /* Flex controller area network 2 message buffer*/
  .word CAN2_Bus_Off_IRQHandler              /* Flex controller area network 2 bus off*/
  .word CAN2_Error_IRQHandler                /* Flex controller area network 2 error*/
  .word CAN2_Tx_Warning_IRQHandler           /* Flex controller area network 2 transmit*/
  .word CAN2_Rx_Warning_IRQHandler           /* Flex controller area network 2 receive*/
  .word CAN2_Wake_Up_IRQHandler              /* Flex controller area network 2 wake up*/

/**
**===========================================================================
**  Flash configuration field
**===========================================================================
*/
.section .flash_cfg,"a", %progbits
FlashConfig:
  .word 0xffffffff     /* 0x400 Backdoor Comparison Key */
  .word 0xffffffff     /* 0x404 Backdoor Comparison Key */
  .word 0xffffffff     
  .word 0xfffffffe     


/**
**===========================================================================
**  Weak interrupt handlers redirected to Default_Handler. These can be
**  overridden in user code.
**===========================================================================
*/
  .weak NMI_Handler
  .thumb_set NMI_Handler, Default_Handler

  .weak HardFault_Handler
  .thumb_set HardFault_Handler, Default_Handler

  .weak MemManage_Handler
  .thumb_set MemManage_Handler, Default_Handler

  .weak BusFault_Handler
  .thumb_set BusFault_Handler, Default_Handler

  .weak UsageFault_Handler
  .thumb_set UsageFault_Handler, Default_Handler

  .weak SVC_Handler
  .thumb_set SVC_Handler, Default_Handler

  .weak DebugMon_Handler
  .thumb_set DebugMon_Handler, Default_Handler

  .weak PendSV_Handler
  .thumb_set PendSV_Handler, Default_Handler

  .weak SysTick_Handler
  .thumb_set SysTick_Handler, Default_Handler

  .weak DMA0_DMA16_IRQHandler
  .thumb_set DMA0_DMA16_IRQHandler, Default_Handler

  .weak DMA1_DMA17_IRQHandler
  .thumb_set DMA1_DMA17_IRQHandler, Default_Handler

  .weak DMA2_DMA18_IRQHandler
  .thumb_set DMA2_DMA18_IRQHandler, Default_Handler

  .weak DMA3_DMA19_IRQHandler
  .thumb_set DMA3_DMA19_IRQHandler, Default_Handler

  .weak DMA4_DMA20_IRQHandler
  .thumb_set DMA4_DMA20_IRQHandler, Default_Handler

  .weak DMA5_DMA21_IRQHandler
  .thumb_set DMA5_DMA21_IRQHandler, Default_Handler

  .weak DMA6_DMA22_IRQHandler
  .thumb_set DMA6_DMA22_IRQHandler, Default_Handler

  .weak DMA7_DMA23_IRQHandler
  .thumb_set DMA7_DMA23_IRQHandler, Default_Handler

  .weak DMA8_DMA24_IRQHandler
  .thumb_set DMA8_DMA24_IRQHandler, Default_Handler

  .weak DMA9_DMA25_IRQHandler
  .thumb_set DMA9_DMA25_IRQHandler, Default_Handler

  .weak DMA10_DMA26_IRQHandler
  .thumb_set DMA10_DMA26_IRQHandler, Default_Handler

  .weak DMA11_DMA27_IRQHandler
  .thumb_set DMA11_DMA27_IRQHandler, Default_Handler

  .weak DMA12_DMA28_IRQHandler
  .thumb_set DMA12_DMA28_IRQHandler, Default_Handler

  .weak DMA13_DMA29_IRQHandler
  .thumb_set DMA13_DMA29_IRQHandler, Default_Handler

  .weak DMA14_DMA30_IRQHandler
  .thumb_set DMA14_DMA30_IRQHandler, Default_Handler

  .weak DMA15_DMA31_IRQHandler
  .thumb_set DMA15_DMA31_IRQHandler, Default_Handler

  .weak DMA_Error_IRQHandler
  .thumb_set DMA_Error_IRQHandler, Default_Handler

  .weak MCM_IRQHandler
  .thumb_set MCM_IRQHandler, Default_Handler

  .weak FTFE_IRQHandler
  .thumb_set FTFE_IRQHandler, Default_Handler

  .weak Read_Collision_IRQHandler
  .thumb_set Read_Collision_IRQHandler, Default_Handler

  .weak PMC_IRQHandler
  .thumb_set PMC_IRQHandler, Default_Handler

  .weak LLWU_IRQHandler
  .thumb_set LLWU_IRQHandler, Default_Handler

  .weak WDOG_EWM_IRQHandler
  .thumb_set WDOG_EWM_IRQHandler, Default_Handler

  .weak TRNG0_IRQHandler
  .thumb_set TRNG0_IRQHandler, Default_Handler

  .weak I2C0_IRQHandler
  .thumb_set I2C0_IRQHandler, Default_Handler

  .weak I2C1_IRQHandler
  .thumb_set I2C1_IRQHandler, Default_Handler

  .weak SPI0_IRQHandler
  .thumb_set SPI0_IRQHandler, Default_Handler

  .weak SPI1_IRQHandler
  .thumb_set SPI1_IRQHandler, Default_Handler

  .weak UART5_RX_TX_IRQHandler
  .thumb_set UART5_RX_TX_IRQHandler, Default_Handler

  .weak UART5_ERR_IRQHandler
  .thumb_set UART5_ERR_IRQHandler, Default_Handler

  .weak UART0_LON_IRQHandler
  .thumb_set UART0_LON_IRQHandler, Default_Handler

  .weak UART0_RX_TX_IRQHandler
  .thumb_set UART0_RX_TX_IRQHandler, Default_Handler

  .weak UART0_ERR_IRQHandler
  .thumb_set UART0_ERR_IRQHandler, Default_Handler

  .weak UART1_RX_TX_IRQHandler
  .thumb_set UART1_RX_TX_IRQHandler, Default_Handler

  .weak UART1_ERR_IRQHandler
  .thumb_set UART1_ERR_IRQHandler, Default_Handler

  .weak UART2_RX_TX_IRQHandler
  .thumb_set UART2_RX_TX_IRQHandler, Default_Handler

  .weak UART2_ERR_IRQHandler
  .thumb_set UART2_ERR_IRQHandler, Default_Handler

  .weak ADC0_IRQHandler
  .thumb_set ADC0_IRQHandler, Default_Handler

  .weak HSADC_ERR_IRQHandler
  .thumb_set HSADC_ERR_IRQHandler, Default_Handler

  .weak HSADC0_CCA_IRQHandler
  .thumb_set HSADC0_CCA_IRQHandler, Default_Handler

  .weak CMP0_IRQHandler
  .thumb_set CMP0_IRQHandler, Default_Handler

  .weak CMP1_IRQHandler
  .thumb_set CMP1_IRQHandler, Default_Handler

  .weak FTM0_IRQHandler
  .thumb_set FTM0_IRQHandler, Default_Handler

  .weak FTM1_IRQHandler
  .thumb_set FTM1_IRQHandler, Default_Handler

  .weak UART3_RX_TX_IRQHandler
  .thumb_set UART3_RX_TX_IRQHandler, Default_Handler

  .weak UART3_ERR_IRQHandler
  .thumb_set UART3_ERR_IRQHandler, Default_Handler

  .weak UART4_RX_TX_IRQHandler
  .thumb_set UART4_RX_TX_IRQHandler, Default_Handler

  .weak UART4_ERR_IRQHandler
  .thumb_set UART4_ERR_IRQHandler, Default_Handler

  .weak PIT0_IRQHandler
  .thumb_set PIT0_IRQHandler, Default_Handler

  .weak PIT1_IRQHandler
  .thumb_set PIT1_IRQHandler, Default_Handler

  .weak PIT2_IRQHandler
  .thumb_set PIT2_IRQHandler, Default_Handler

  .weak PIT3_IRQHandler
  .thumb_set PIT3_IRQHandler, Default_Handler

  .weak PDB0_IRQHandler
  .thumb_set PDB0_IRQHandler, Default_Handler

  .weak FTM2_IRQHandler
  .thumb_set FTM2_IRQHandler, Default_Handler

  .weak XBARA_IRQHandler
  .thumb_set XBARA_IRQHandler, Default_Handler

  .weak PDB1_IRQHandler
  .thumb_set PDB1_IRQHandler, Default_Handler

  .weak DAC0_IRQHandler
  .thumb_set DAC0_IRQHandler, Default_Handler

  .weak MCG_IRQHandler
  .thumb_set MCG_IRQHandler, Default_Handler

  .weak LPTMR0_IRQHandler
  .thumb_set LPTMR0_IRQHandler, Default_Handler

  .weak PORTA_IRQHandler
  .thumb_set PORTA_IRQHandler, Default_Handler

  .weak PORTB_IRQHandler
  .thumb_set PORTB_IRQHandler, Default_Handler

  .weak PORTC_IRQHandler
  .thumb_set PORTC_IRQHandler, Default_Handler

  .weak PORTD_IRQHandler
  .thumb_set PORTD_IRQHandler, Default_Handler

  .weak PORTE_IRQHandler
  .thumb_set PORTE_IRQHandler, Default_Handler

  .weak SWI_IRQHandler
  .thumb_set SWI_IRQHandler, Default_Handler

  .weak SPI2_IRQHandler
  .thumb_set SPI2_IRQHandler, Default_Handler

  .weak ENC_COMPARE_IRQHandler
  .thumb_set ENC_COMPARE_IRQHandler, Default_Handler

  .weak ENC_HOME_IRQHandler
  .thumb_set ENC_HOME_IRQHandler, Default_Handler

  .weak ENC_WDOG_SAB_IRQHandler
  .thumb_set ENC_WDOG_SAB_IRQHandler, Default_Handler

  .weak ENC_INDEX_IRQHandler
  .thumb_set ENC_INDEX_IRQHandler, Default_Handler

  .weak CMP2_IRQHandler
  .thumb_set CMP2_IRQHandler, Default_Handler

  .weak FTM3_IRQHandler
  .thumb_set FTM3_IRQHandler, Default_Handler

  .weak Reserved88_IRQHandler
  .thumb_set Reserved88_IRQHandler, Default_Handler

  .weak HSADC0_CCB_IRQHandler
  .thumb_set HSADC0_CCB_IRQHandler, Default_Handler

  .weak HSADC1_CCA_IRQHandler
  .thumb_set HSADC1_CCA_IRQHandler, Default_Handler

  .weak CAN0_ORed_Message_buffer_IRQHandler
  .thumb_set CAN0_ORed_Message_buffer_IRQHandler, Default_Handler

  .weak CAN0_Bus_Off_IRQHandler
  .thumb_set CAN0_Bus_Off_IRQHandler, Default_Handler

  .weak CAN0_Error_IRQHandler
  .thumb_set CAN0_Error_IRQHandler, Default_Handler

  .weak CAN0_Tx_Warning_IRQHandler
  .thumb_set CAN0_Tx_Warning_IRQHandler, Default_Handler

  .weak CAN0_Rx_Warning_IRQHandler
  .thumb_set CAN0_Rx_Warning_IRQHandler, Default_Handler

  .weak CAN0_Wake_Up_IRQHandler
  .thumb_set CAN0_Wake_Up_IRQHandler, Default_Handler

  .weak PWM0_CMP0_IRQHandler
  .thumb_set PWM0_CMP0_IRQHandler, Default_Handler

  .weak PWM0_RELOAD0_IRQHandler
  .thumb_set PWM0_RELOAD0_IRQHandler, Default_Handler

  .weak PWM0_CMP1_IRQHandler
  .thumb_set PWM0_CMP1_IRQHandler, Default_Handler

  .weak PWM0_RELOAD1_IRQHandler
  .thumb_set PWM0_RELOAD1_IRQHandler, Default_Handler

  .weak PWM0_CMP2_IRQHandler
  .thumb_set PWM0_CMP2_IRQHandler, Default_Handler

  .weak PWM0_RELOAD2_IRQHandler
  .thumb_set PWM0_RELOAD2_IRQHandler, Default_Handler

  .weak PWM0_CMP3_IRQHandler
  .thumb_set PWM0_CMP3_IRQHandler, Default_Handler

  .weak PWM0_RELOAD3_IRQHandler
  .thumb_set PWM0_RELOAD3_IRQHandler, Default_Handler

  .weak PWM0_CAP_IRQHandler
  .thumb_set PWM0_CAP_IRQHandler, Default_Handler

  .weak PWM0_RERR_IRQHandler
  .thumb_set PWM0_RERR_IRQHandler, Default_Handler

  .weak PWM0_FAULT_IRQHandler
  .thumb_set PWM0_FAULT_IRQHandler, Default_Handler

  .weak CMP3_IRQHandler
  .thumb_set CMP3_IRQHandler, Default_Handler

  .weak HSADC1_CCB_IRQHandler
  .thumb_set HSADC1_CCB_IRQHandler, Default_Handler

  .weak CAN1_ORed_Message_buffer_IRQHandler
  .thumb_set CAN1_ORed_Message_buffer_IRQHandler, Default_Handler

  .weak CAN1_Bus_Off_IRQHandler
  .thumb_set CAN1_Bus_Off_IRQHandler, Default_Handler

  .weak CAN1_Error_IRQHandler
  .thumb_set CAN1_Error_IRQHandler, Default_Handler

  .weak CAN1_Tx_Warning_IRQHandler
  .thumb_set CAN1_Tx_Warning_IRQHandler, Default_Handler

  .weak CAN1_Rx_Warning_IRQHandler
  .thumb_set CAN1_Rx_Warning_IRQHandler, Default_Handler

  .weak CAN1_Wake_Up_IRQHandler
  .thumb_set CAN1_Wake_Up_IRQHandler, Default_Handler

  .weak ENET_1588_Timer_IRQHandler
  .thumb_set ENET_1588_Timer_IRQHandler, Default_Handler

  .weak ENET_Transmit_IRQHandler
  .thumb_set ENET_Transmit_IRQHandler, Default_Handler

  .weak ENET_Receive_IRQHandler
  .thumb_set ENET_Receive_IRQHandler, Default_Handler

  .weak ENET_Error_IRQHandler
  .thumb_set ENET_Error_IRQHandler, Default_Handler

  .weak PWM1_CMP0_IRQHandler
  .thumb_set PWM1_CMP0_IRQHandler, Default_Handler

  .weak PWM1_RELOAD0_IRQHandler
  .thumb_set PWM1_RELOAD0_IRQHandler, Default_Handler

  .weak PWM1_CMP1_IRQHandler
  .thumb_set PWM1_CMP1_IRQHandler, Default_Handler

  .weak PWM1_RELOAD1_IRQHandler
  .thumb_set PWM1_RELOAD1_IRQHandler, Default_Handler

  .weak PWM1_CMP2_IRQHandler
  .thumb_set PWM1_CMP2_IRQHandler, Default_Handler

  .weak PWM1_RELOAD2_IRQHandler
  .thumb_set PWM1_RELOAD2_IRQHandler, Default_Handler

  .weak PWM1_CMP3_IRQHandler
  .thumb_set PWM1_CMP3_IRQHandler, Default_Handler

  .weak PWM1_RELOAD3_IRQHandler
  .thumb_set PWM1_RELOAD3_IRQHandler, Default_Handler

  .weak PWM1_CAP_IRQHandler
  .thumb_set PWM1_CAP_IRQHandler, Default_Handler

  .weak PWM1_RERR_IRQHandler
  .thumb_set PWM1_RERR_IRQHandler, Default_Handler

  .weak PWM1_FAULT_IRQHandler
  .thumb_set PWM1_FAULT_IRQHandler, Default_Handler

  .weak CAN2_ORed_Message_buffer_IRQHandler
  .thumb_set CAN2_ORed_Message_buffer_IRQHandler, Default_Handler

  .weak CAN2_Bus_Off_IRQHandler
  .thumb_set CAN2_Bus_Off_IRQHandler, Default_Handler

  .weak CAN2_Error_IRQHandler
  .thumb_set CAN2_Error_IRQHandler, Default_Handler

  .weak CAN2_Tx_Warning_IRQHandler
  .thumb_set CAN2_Tx_Warning_IRQHandler, Default_Handler

  .weak CAN2_Rx_Warning_IRQHandler
  .thumb_set CAN2_Rx_Warning_IRQHandler, Default_Handler

  .weak CAN2_Wake_Up_IRQHandler
  .thumb_set CAN2_Wake_Up_IRQHandler, Default_Handler

  .end
